name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 'rjeff5/Terraform-Sessions'  # Replace with your GitHub repository URL
          path: 'Conditional'  # Replace with the subdirectory where your Terraform code is located
          
      - name: Run Commands in Conditional directory
        run: |
          cd Conditional
          pwd
          ls
          # Add other commands here as needed
          terraform init
          terraform plan
          terraform apply -auto-approve
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
